name: Test School Python 01

on:
  pull_request_target:
    branches: ["main", "master"]

jobs:
  test-project:
    uses: cx-actions-2025/fm-actions/.github/workflows/school-python1.yaml@03cc19508f907ab8f40790b8570417c60572995f
    with:
        team-name: ${{ vars.TEAM_NAME }}
        pr_head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
        test-repo: ${{ secrets.TEST_REPO }}
        auth-token: ${{ secrets.AUTH_TOKEN }}
        backend-url: ${{ secrets.BACKEND_URL }}
        auth-key: ${{ secrets.AUTH_KEY }}